//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registers.Forms.LisanceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LisansTaleb", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LisansTaleb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        private System.DateTime TarixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HDD {
            get {
                return this.HDDField;
            }
            set {
                if ((object.ReferenceEquals(this.HDDField, value) != true)) {
                    this.HDDField = value;
                    this.RaisePropertyChanged("HDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Tarix {
            get {
                return this.TarixField;
            }
            set {
                if ((this.TarixField.Equals(value) != true)) {
                    this.TarixField = value;
                    this.RaisePropertyChanged("Tarix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LisansCavab", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LisansCavab : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DogurlulamaKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HDDField;
        
        private System.DateTime TarixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DogurlulamaKodu {
            get {
                return this.DogurlulamaKoduField;
            }
            set {
                if ((this.DogurlulamaKoduField.Equals(value) != true)) {
                    this.DogurlulamaKoduField = value;
                    this.RaisePropertyChanged("DogurlulamaKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HDD {
            get {
                return this.HDDField;
            }
            set {
                if ((object.ReferenceEquals(this.HDDField, value) != true)) {
                    this.HDDField = value;
                    this.RaisePropertyChanged("HDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Tarix {
            get {
                return this.TarixField;
            }
            set {
                if ((this.TarixField.Equals(value) != true)) {
                    this.TarixField = value;
                    this.RaisePropertyChanged("Tarix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LisanceService.LisensSoap")]
    public interface LisensSoap {
        
        // CODEGEN: Generating message contract since element name taleb from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LisansDogrulama", ReplyAction="*")]
        Registers.Forms.LisanceService.LisansDogrulamaResponse LisansDogrulama(Registers.Forms.LisanceService.LisansDogrulamaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LisansDogrulama", ReplyAction="*")]
        System.Threading.Tasks.Task<Registers.Forms.LisanceService.LisansDogrulamaResponse> LisansDogrulamaAsync(Registers.Forms.LisanceService.LisansDogrulamaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LisansDogrulamaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LisansDogrulama", Namespace="http://tempuri.org/", Order=0)]
        public Registers.Forms.LisanceService.LisansDogrulamaRequestBody Body;
        
        public LisansDogrulamaRequest() {
        }
        
        public LisansDogrulamaRequest(Registers.Forms.LisanceService.LisansDogrulamaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LisansDogrulamaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Registers.Forms.LisanceService.LisansTaleb taleb;
        
        public LisansDogrulamaRequestBody() {
        }
        
        public LisansDogrulamaRequestBody(Registers.Forms.LisanceService.LisansTaleb taleb) {
            this.taleb = taleb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LisansDogrulamaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LisansDogrulamaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Registers.Forms.LisanceService.LisansDogrulamaResponseBody Body;
        
        public LisansDogrulamaResponse() {
        }
        
        public LisansDogrulamaResponse(Registers.Forms.LisanceService.LisansDogrulamaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LisansDogrulamaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Registers.Forms.LisanceService.LisansCavab LisansDogrulamaResult;
        
        public LisansDogrulamaResponseBody() {
        }
        
        public LisansDogrulamaResponseBody(Registers.Forms.LisanceService.LisansCavab LisansDogrulamaResult) {
            this.LisansDogrulamaResult = LisansDogrulamaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LisensSoapChannel : Registers.Forms.LisanceService.LisensSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LisensSoapClient : System.ServiceModel.ClientBase<Registers.Forms.LisanceService.LisensSoap>, Registers.Forms.LisanceService.LisensSoap {
        
        public LisensSoapClient() {
        }
        
        public LisensSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LisensSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisensSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisensSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Registers.Forms.LisanceService.LisansDogrulamaResponse Registers.Forms.LisanceService.LisensSoap.LisansDogrulama(Registers.Forms.LisanceService.LisansDogrulamaRequest request) {
            return base.Channel.LisansDogrulama(request);
        }
        
        public Registers.Forms.LisanceService.LisansCavab LisansDogrulama(Registers.Forms.LisanceService.LisansTaleb taleb) {
            Registers.Forms.LisanceService.LisansDogrulamaRequest inValue = new Registers.Forms.LisanceService.LisansDogrulamaRequest();
            inValue.Body = new Registers.Forms.LisanceService.LisansDogrulamaRequestBody();
            inValue.Body.taleb = taleb;
            Registers.Forms.LisanceService.LisansDogrulamaResponse retVal = ((Registers.Forms.LisanceService.LisensSoap)(this)).LisansDogrulama(inValue);
            return retVal.Body.LisansDogrulamaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Registers.Forms.LisanceService.LisansDogrulamaResponse> Registers.Forms.LisanceService.LisensSoap.LisansDogrulamaAsync(Registers.Forms.LisanceService.LisansDogrulamaRequest request) {
            return base.Channel.LisansDogrulamaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Registers.Forms.LisanceService.LisansDogrulamaResponse> LisansDogrulamaAsync(Registers.Forms.LisanceService.LisansTaleb taleb) {
            Registers.Forms.LisanceService.LisansDogrulamaRequest inValue = new Registers.Forms.LisanceService.LisansDogrulamaRequest();
            inValue.Body = new Registers.Forms.LisanceService.LisansDogrulamaRequestBody();
            inValue.Body.taleb = taleb;
            return ((Registers.Forms.LisanceService.LisensSoap)(this)).LisansDogrulamaAsync(inValue);
        }
    }
}
